const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL';

const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
const USER_FETCH_FAIL = 'USER_FETCH_FAIL';

const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
const USER_ADD_FAIL = 'USER_ADD_FAIL';

const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
const USER_EDIT_FAIL = 'USER_EDIT_FAIL';

const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export {
  USERS_FETCH_REQUEST,
  USERS_FETCH_SUCCESS,
  USERS_FETCH_FAIL,
  USER_FETCH_REQUEST,
  USER_FETCH_SUCCESS,
  USER_FETCH_FAIL,
  USER_ADD_REQUEST,
  USER_ADD_SUCCESS,
  USER_ADD_FAIL,
  USER_EDIT_REQUEST,
  USER_EDIT_SUCCESS,
  USER_EDIT_FAIL,
  USER_DELETE_REQUEST,
  USER_DELETE_SUCCESS,
  USER_DELETE_FAIL,
};
